## 利用GitHub Actions每天定时给百度推送链接，提高收录率 ##

name: hnSpider

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
on: 
   push:
    branches:
      - main
   schedule:
    - cron:  '*/30 9 * * *'


jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      env:
        clientSecret: ${{ secrets.clientSecret }}
        privateKey: ${{ secrets.privateKey }}
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: 'Run hnSpider'  # 步骤二，执行sh命令文件
        run: npm install && npm run hnSpider # 运行目录是仓库根目录
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: hacker new dayly.
          tagging_message: 'v2.0.0'
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: 1216226589@qq.com # defaults to "actions@github.com"
